name: Build/Test

on:
  push:
  pull_request:

env:
  MAKE_BUILD_FLAGS: -j2
  GRID_REPOSITORY_REF: feature/gpt
  CC: mpicc
  CXX: mpic++
  OMPI_CC: cc
  OMPI_CXX: c++
  MPICH_CC: cc
  MPICH_CXX: c++
  # Note if this is changed, all caches will be not be valid anymore
  CACHE_KEY: 2020-06-05

jobs:
  build-grid:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        compiler: ['gcc', 'clang']
        mpi: ['none', 'mpich', 'openmpi']

    outputs:
      c-lime-version: ${{ steps.c-lime-version.outputs.key }}
      grid-version: ${{ steps.grid-version.outputs.key }}

    steps:
    - name: Check Hardware
      run: |
        cat /proc/cpuinfo | grep avx2

    - name: Install Ubuntu packages
      run: |
        sudo apt-get install -y clang-9 libmpfr-dev libgmp-dev libssl-dev zlib1g-dev libmpich-dev libopenmpi-dev

    - name: Set compiler alternatives to clang-9
      if: matrix.compiler == 'clang'
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 1
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 1

        sudo update-alternatives --set cc /usr/bin/clang-9
        sudo update-alternatives --set c++ /usr/bin/clang++-9

        echo '::set-env name=LDFLAGS::-lomp'

    - name: Set compiler to cc and c++
      if: matrix.mpi == 'none'
      run: |
        echo '::set-env name=CC::cc'
        echo '::set-env name=CXX::c++'

    - name: Set MPI alternatives to mpich
      if: matrix.mpi == 'mpich'
      run: |
        sudo update-alternatives --set mpi /usr/include/mpich
        sudo update-alternatives --set mpirun /usr/bin/mpirun.mpich

    - name: Clone c-lime
      uses: actions/checkout@v2
      with:
        repository: usqcd-software/c-lime
        path: c-lime

    - name: Get c-lime cache key
      id: c-lime-version
      run: |
        cd c-lime
        echo "::set-output name=key::$(git rev-parse HEAD)-${CACHE_KEY}"

    - name: c-lime package cache
      uses: actions/cache@v2
      id: c-lime-package-cache
      with:
        path: c-lime-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb
        key: c-lime-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ steps.c-lime-version.outputs.key }}

    - name: Build and package c-lime
      if: steps.c-lime-package-cache.outputs.cache-hit != 'true'
      run: |
        PKGDIR=$PWD/c-lime-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}
        mkdir -p $PKGDIR
        cd c-lime
        ./autogen.sh
        ./configure || cat config.log
        make ${MAKE_BUILD_FLAGS}
        DESTDIR=$PKGDIR make install

        cd $PKGDIR
        mkdir -p DEBIAN
        wget -nv -O ./DEBIAN/control https://gist.githubusercontent.com/lehner/a0feb168a9cb2068e0345a94b2df2eb9/raw/79dd47ef34aa7166191c7d8293372bcb4b9a5533/deb.general.control
        sed -e 's/%pkgname%/c-lime/g' -e 's/%version%/0.0.1/g' -e 's/%size%/1024/g' -e 's/%maintainer%/GPT Dev Team/g' -e 's/%description%/C-LIME/g'  -i ./DEBIAN/control
        cd -
        dpkg-deb --build $PKGDIR

    - name: Install c-lime
      run: |
        sudo dpkg -i c-lime-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb

    - name: Clone Grid
      uses: actions/checkout@v2
      with:
        repository: lehner/Grid
        ref: ${{ env.GRID_REPOSITORY_REF }}
        path: Grid

    - name: Get Grid cache key
      id: grid-version
      run: |
        cd Grid
        ./bootstrap.sh
        mkdir -p build
        cd build

        if [ "${{ matrix.mpi }}" == "none" ]
        then
            ../configure CXXFLAGS=-fPIC --enable-simd=AVX2 || cat config.log
        else
            ../configure CXXFLAGS=-fPIC --enable-simd=AVX2 --enable-comms=mpi-auto || cat config.log
        fi

        cd Grid
        make version-cache Version.h
        echo "::set-output name=key::$(sha256sum version-cache|cut -f 1 -d " ")-${CACHE_KEY}"

    - name: Grid package cache
      uses: actions/cache@v2
      id: grid-package-cache
      with:
        path: grid-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb
        key: grid-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ steps.grid-version.outputs.key }}

    - name: Build and package Grid
      if: steps.grid-package-cache.outputs.cache-hit != 'true'
      run: |
        PKGDIR=$PWD/grid-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}
        mkdir -p $PKGDIR
        cd Grid/build/Grid
        make ${MAKE_BUILD_FLAGS}
        DESTDIR=$PKGDIR make install
        cd .. && install -D -m755 grid-config ${PKGDIR}/usr/bin/grid-config || return 1

        cd $PKGDIR
        mkdir -p DEBIAN
        wget -nv -O ./DEBIAN/control https://gist.githubusercontent.com/lehner/a0feb168a9cb2068e0345a94b2df2eb9/raw/79dd47ef34aa7166191c7d8293372bcb4b9a5533/deb.general.control
        sed -e 's/%pkgname%/grid/g' -e 's/%version%/0.0.1/g' -e 's/%size%/1024/g' -e 's/%maintainer%/GPT Dev Team/g' -e 's/%description%/Grid/g'  -i ./DEBIAN/control
        cd -
        dpkg-deb --build $PKGDIR

    - name: Install Grid
      run: |
        sudo dpkg -i grid-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb


  build-gpt:
    needs: build-grid
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
        compiler: ['gcc', 'clang']
        mpi: ['none', 'mpich', 'openmpi']

    outputs:
      cgpt-version: ${{ steps.cgpt-version.outputs.key }}
      gpt-version: ${{ steps.gpt-version.outputs.key }}
      python-gpt-version: ${{ steps.python-gpt-version.outputs.version }}

    steps:
    - name: Check Hardware
      run: |
        cat /proc/cpuinfo | grep avx2

    - name: Install Ubuntu packages
      run: |
        sudo apt-get install -y clang-9 libmpfr-dev libgmp-dev libssl-dev zlib1g-dev libmpich-dev libopenmpi-dev

    - name: Set compiler alternatives to clang-9
      if: matrix.compiler == 'clang'
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 1
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 1

        sudo update-alternatives --set cc /usr/bin/clang-9
        sudo update-alternatives --set c++ /usr/bin/clang++-9
        echo '::set-env name=LDFLAGS::-lomp'

    - name: Set MPI alternatives to mpich
      if: matrix.mpi == 'mpich'
      run: |
        sudo update-alternatives --set mpi /usr/include/mpich
        sudo update-alternatives --set mpirun /usr/bin/mpirun.mpich

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Setup python dependencies
      run: |
        pip install numpy

    - name: c-lime package cache
      uses: actions/cache@v2
      id: c-lime-package-cache
      with:
        path: c-lime-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb
        key: c-lime-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ needs.build-grid.outputs.c-lime-version }}

    - name: Install c-lime
      run: |
        sudo dpkg -i c-lime-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb

    - name: Grid package cache
      uses: actions/cache@v2
      id: grid-package-cache
      with:
        path: grid-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb
        key: grid-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ needs.build-grid.outputs.grid-version }}

    - name: Install Grid
      run: |
        sudo dpkg -i grid-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb

    - name: Clone gpt
      uses: actions/checkout@v2
      with:
        path: gpt

    - name: Get cgpt cache key
      id: cgpt-version
      # Currently it is not possible to use multiple patterns with hashFiles, therefore we use our own hashing, see:
      # https://github.community/t/hashfiles-with-multiple-patterns/17168
      run: |
        # TODO: if the make and make.summit files are removed from ./gpt/lib/cgpt we can use the complete folder for hashing
        echo ${{ hashFiles('gpt/lib/cgpt/lib/**') }} >> cgpt_cache_key_file
        echo ${{ hashFiles('gpt/bootstrap.sh') }} >> cgpt_cache_key_file
        echo ${{ hashFiles('gpt/configure.ac') }} >> cgpt_cache_key_file
        echo ${{ hashFiles('gpt/Makefile.am') }} >> cgpt_cache_key_file
        echo ${{ hashFiles('gpt/cgpt/Makefile.am') }} >> cgpt_cache_key_file

        echo "::set-output name=key::$(sha256sum cgpt_cache_key_file|cut -f 1 -d " ")-${CACHE_KEY}"

    - name: Get gpt cache key
      id: gpt-version
      # Currently it is not possible to use multiple patterns with hashFiles, therefore we use our own hashing, see:
      # https://github.community/t/hashfiles-with-multiple-patterns/17168
      run: |
        echo ${{ hashFiles('gpt/lib/gpt/**') }} >> gpt_cache_key_file
        echo ${{ hashFiles('gpt/bootstrap.sh') }} >> gpt_cache_key_file
        echo ${{ hashFiles('gpt/configure.ac') }} >> gpt_cache_key_file
        echo ${{ hashFiles('gpt/Makefile.am') }} >> gpt_cache_key_file

        echo "::set-output name=key::$(sha256sum gpt_cache_key_file|cut -f 1 -d " ")-${CACHE_KEY}"

    - name: Get python-gpt version
      id: python-gpt-version
      run: |
        gpt_version=$(printf "0.0.0r%s" "$(cd gpt && git rev-parse --short HEAD)")
        echo "::set-output name=version::${gpt_version}"

    - name: cgpt package cache
      uses: actions/cache@v2
      id: cgpt-package-cache
      with:
        path: cgpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb
        key: cgpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ steps.cgpt-version.outputs.key }}

    - name: Build and package cgpt
      if: steps.cgpt-package-cache.outputs.cache-hit != 'true'
      run: |
        PKGDIR=$PWD/cgpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}
        mkdir -p $PKGDIR
        cd gpt
        ./bootstrap.sh
        mkdir -p build
        cd build
        ../configure --disable-gpt || cat config.log
        make ${MAKE_BUILD_FLAGS}
        DESTDIR=$PKGDIR make install

        cd $PKGDIR
        mkdir -p DEBIAN
        wget -nv -O ./DEBIAN/control https://gist.githubusercontent.com/lehner/a0feb168a9cb2068e0345a94b2df2eb9/raw/79dd47ef34aa7166191c7d8293372bcb4b9a5533/deb.general.control
        sed -e 's/%pkgname%/cgpt/g' -e 's/%version%/0.0.1/g' -e 's/%size%/1024/g' -e 's/%maintainer%/GPT Dev Team/g' -e 's/%description%/cgpt/g'  -i ./DEBIAN/control
        cd -
        dpkg-deb --build $PKGDIR

    - name: Install cgpt
      run: |
        sudo dpkg -i cgpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb

    - name: gpt package cache
      uses: actions/cache@v2
      id: gpt-package-cache
      with:
        path: gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb
        key: gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ steps.gpt-version.outputs.key }}

    - name: Build and package gpt
      if: steps.gpt-package-cache.outputs.cache-hit != 'true'
      run: |
        PKGDIR=$PWD/gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}
        mkdir -p $PKGDIR
        cd gpt
        ./bootstrap.sh
        mkdir -p build
        cd build
        ../configure --disable-cgpt || cat config.log
        make ${MAKE_BUILD_FLAGS}
        DESTDIR=$PKGDIR make install

        cd $PKGDIR
        mkdir -p DEBIAN
        wget -nv -O ./DEBIAN/control https://gist.githubusercontent.com/lehner/a0feb168a9cb2068e0345a94b2df2eb9/raw/79dd47ef34aa7166191c7d8293372bcb4b9a5533/deb.general.control
        sed -e 's/%pkgname%/gpt/g' -e 's/%version%/0.0.1/g' -e 's/%size%/1024/g' -e 's/%maintainer%/GPT Dev Team/g' -e 's/%description%/gpt/g'  -i ./DEBIAN/control
        cd -
        dpkg-deb --build $PKGDIR

    - name: Install gpt
      run: |
        sudo dpkg -i gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb

    - name: Create combined package
      run: |
        PKGDIR=$PWD/python-gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}

        dpkg-deb -X gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb ${PKGDIR}
        dpkg-deb -X cgpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb ${PKGDIR}

        cd ${PKGDIR}
        mkdir -p DEBIAN
        wget -nv -O ./DEBIAN/control https://gist.githubusercontent.com/lehner/a0feb168a9cb2068e0345a94b2df2eb9/raw/79dd47ef34aa7166191c7d8293372bcb4b9a5533/deb.general.control
        sed -e 's/%pkgname%/python-gpt/g' \
          -e "s/%version%/${{ steps.python-gpt-version.outputs.version }}/g" \
          -e "s/%size%/$(du -sk .|grep --color=never -E '[0-9]+' -o)/g" \
          -e 's/%maintainer%/GPT Dev Team/g' -e 's/%description%/gpt/g' -i ./DEBIAN/control
        cd -
        dpkg-deb --build $PKGDIR

    - name: Create artifact for python-gpt package
      uses: actions/upload-artifact@v1
      with:
        path: python-gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb
        name: python-gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ steps.python-gpt-version.outputs.version }}

  test-gpt:
    needs: [build-grid, build-gpt]
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
        compiler: ['gcc', 'clang']
        mpi: ['none', 'mpich', 'openmpi']

    steps:
    - name: Report Hardware
      run: |
        cat /proc/cpuinfo

    - name: Install Ubuntu packages
      run: |
        sudo apt-get install -y clang-9 libmpfr-dev libgmp-dev libssl-dev zlib1g-dev libmpich-dev libopenmpi-dev

    - name: Set compiler alternatives to clang-9
      if: matrix.compiler == 'clang'
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 1
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 1

        sudo update-alternatives --set cc /usr/bin/clang-9
        sudo update-alternatives --set c++ /usr/bin/clang++-9
        echo '::set-env name=LDFLAGS::-lomp'

    - name: Set MPI alternatives to mpich
      if: matrix.mpi == 'mpich'
      run: |
        sudo update-alternatives --set mpi /usr/include/mpich
        sudo update-alternatives --set mpirun /usr/bin/mpirun.mpich

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Setup python dependencies
      run: |
        pip install numpy

    - name: Download prebuild python-gpt
      uses: actions/download-artifact@v2
      with:
        name: python-gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}-${{ needs.build-gpt.outputs.python-gpt-version }}

    - name: Install python-gpt
      run: |
        sudo dpkg -i python-gpt-${{ runner.os }}-python-${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.mpi }}.deb

    - name: Clone gpt
      uses: actions/checkout@v2
      with:
        path: gpt

    - name: Run tests
      if: matrix.mpi == 'none'
      run: |
        cd gpt/tests
        export PYTHONPATH=/usr/local/lib/python${{ matrix.python-version}}/site-packages:/usr/local/lib64/python${{ matrix.python-version}}/site-packages
        ./run

    - name: Run tests
      if: matrix.mpi == 'openmpi'
      env:
        LD_PRELOAD: libmpi.so
      run: |
        cd gpt/tests
        export PYTHONPATH=/usr/local/lib/python${{ matrix.python-version}}/site-packages:/usr/local/lib64/python${{ matrix.python-version}}/site-packages
        mpirun -np 2 -mca btl ^openib -bind-to core python core/scalar.py --mpi 1.1.1.2
        ./run "mpirun -np 1 -mca btl ^openib python"
        ./run "mpirun -np 2 -bind-to core -mca btl ^openib python" "--mpi 1.1.1.2 --mpi 1.1.2"

    - name: Run tests
      if: matrix.mpi == 'mpich'
      run: |
        export PYTHONPATH=/usr/local/lib/python${{ matrix.python-version}}/site-packages:/usr/local/lib64/python${{ matrix.python-version}}/site-packages
        cd gpt/tests
        ./run "mpirun -np 1 python"
        ./run "mpirun -np 2 -bind-to core python" "--mpi 1.1.1.2 --mpi 1.1.2"
